[package]
edition = "2021"
name = "gmork-cli"
version = "0.1.0"
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[dependencies.clap]
features = ["derive"]
version = "*"
